# config.yaml


# -------- #
# Datasets #
# -------- #

file_name: './extractedData/ACCAD/Male1General_c3d/General A2 - Sway_poses.npz'


# -------- #
# Subjects #
# -------- #

# the number of subjects to load from AMASS datasets
num_subjects: 1000

# the number of subjects to send to GPU and process at each iteration
subject_batch: 100

# -- each subject is duplicated and noised instead of using a loop to noise each subject multiple times
num_subject_duplicates: 50


# ---- #
# Time #
# ---- #

# each copy of a subject X[n] is noised into X[m, n]  where m is in [0, num_time_points - 1]
num_time_points: 128

# the time resoluttion
time_increment: 0.002


# -------- #
# Training #
# -------- #

# the number of training epochs
num_epochs: 4000

# limit the norm of gradient during training, used to prevent overshoot
max_norm: 3.0

# a hyperparameter to tune the training process
learning_rate: 0.00008
